apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: api-key-configmap
  namespace: default
data:
  REDIS: redis-service
---    
apiVersion: apps/v1
kind : Deployment
metadata:
  name: api-key-gen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-key-gen
  template:
    metadata:
      labels:
        app: api-key-gen
    spec:
      containers:
      - name: api-key-gen
        image: pedrofraca/api-key-gen:1.5
        ports:
        - name: server-port
          containerPort: 3000
        env:
          - name: REDIS
            valueFrom:
              configMapKeyRef:
                name: api-key-configmap
                key: REDIS
          - name: SENDGRID_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-key-gen-secrets
                key: SENDGRID_API_KEY
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: api-key-gen-secrets
                key: SECRET
---
apiVersion : v1
kind : Service
metadata:
  name: api-key-gen-service
spec:
  ports:
  - port: 80
    nodePort: 31002
    targetPort: server-port
    protocol: TCP
  selector:
    app: api-key-gen
  type: NodePort